version: '3'

services:
  
  annotator:
    build: ../annotator
    volumes:
      - ../annotator:/code
    ports:
      - 5555:5555
    hostname: backend-service
  
  ui-jinja:
    build: ../ui-jinja
    volumes:
      - ../ui-jinja:/code
    ports:
      - 8080:8080
    depends_on:
      - annotator
    environment:
      PYTHONUNBUFFERED: ${PYTHONUNBUFFERED}
  
  annotator_prediction:
    build: ../annotator_prediction
    volumes:
      - ../annotator_prediction:/code
    ports:
      - 5050:5050